
# این یک ورک‌فلو واحد برای تست، ساخت و انتشار برنامه است

name: Build and Publish

# این ورک‌فلو در هر پوش به برنچ اصلی یا هر پول رکوئست اجرا می‌شود
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-release:
    # از آخرین نسخه اوبونتو برای اجرای جاب استفاده می‌کنیم
    runs-on: ubuntu-latest

    steps:
      # مرحله ۱: کد پروژه را از مخزن گیت دریافت می‌کند
      - name: Checkout repository
        uses: actions/checkout@v4

      # مرحله ۲: نود و npm را نصب می‌کند و از کش برای سرعت بیشتر استفاده می‌کند
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # استفاده از نسخه پایدار نود
          cache: 'npm'

      # مرحله ۳: پکیج‌ها را با استفاده از فایل قفل نصب می‌کند
      # npm ci سریع‌تر و امن‌تر از npm install برای محیط‌های CI است
      - name: Install dependencies
        run: npm ci

      # مرحله ۵: برنامه را برای تمام پلتفرم‌ها پکیج می‌کند
      - name: Build and package application
        run: npm run package

      # مرحله ۶: برنامه را فقط زمانی منتشر می‌کند که یک پوش به برنچ main زده شود
      # این مرحله در پول رکوئست‌ها اجرا نمی‌شود
      - name: Publish to GitHub Releases
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: npm exec electron-builder -- --publish always --win --mac --linux

